DROP TABLE IF EXISTS natural_person;
DROP TABLE IF EXISTS legal_entity;
DROP TABLE IF EXISTS transaction_reasons;
DROP TABLE IF EXISTS business_relationship_types;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS industry_types;
DROP TABLE IF EXISTS product_types;
DROP TABLE IF EXISTS risk_class;
DROP TABLE IF EXISTS source_of_funds;
DROP TABLE IF EXISTS parties;

CREATE TABLE parties (
	id INTEGER PRIMARY KEY,
	party_type TEXT, -- N or L
	party_alert BOOLEAN, -- true or false
	party_is_used BOOLEAN, -- true or false
	firstname TEXT,
	surname TEXT,
	middle_name TEXT,
	previous_surname TEXT,
	date_of_birth TEXT,
	country_of_birth TEXT,
	nationality TEXT,
	country_of_residence TEXT,
	gender TEXT,
	profession TEXT,
	monthly_income INTEGER,
	date_of_last_income TEXT,
	id_number TEXT,
	nationality2 TEXT,
	nationality3 TEXT,
	passport TEXT,
	passport_country TEXT,
	tax_registration_number TEXT,
	primary_tax_residence TEXT,
	foreign_tin TEXT,
	foreign_tin_issuing_country TEXT,
	-- relationship
	reason_for_transaction TEXT, -- Default value will be used when generating the batch file
	product_type TEXT, -- not using this column as values are in the dropdown
	risk_class TEXT, -- not using this column as values are in the dropdown
	business_relationship TEXT, -- Default value will be used when generating the batch file
	source_of_funds TEXT,
	account_number TEXT,
	transaction_amount INTEGER,
	transaction_date TEXT,
	inception_date TEXT,
	authorised_by TEXT,
	termination_date TEXT,
	-- LE details
	registered_name TEXT,
	registration_number TEXT,
	date_of_registration TEXT,
	country_of_registration TEXT,
	industry_type TEXT,
	additional_tax_residence TEXT,
	vat_registration_number TEXT,
	-- NP address information
	np_residential_address TEXT,
	np_postal_address TEXT,
	np_pobox_address TEXT,
	-- LE address information
	le_postal_address TEXT,
	le_pobox_address TEXT,
	le_registered_address TEXT,
	le_gcoheadoffice_address TEXT,
	le_operational_address TEXT
);

CREATE TABLE industry_types (
	id INTEGER PRIMARY KEY,
	name TEXT,
	enabled INTEGER,
	natural_person_enabled INTEGER,
	legal_entity_enabled INTEGER,
	code TEXT
);

CREATE TABLE countries (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    enabled INTEGER NOT NULL,
    risk_profile_id INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE transaction_reasons (
	id INTEGER PRIMARY KEY,
	description TEXT NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	code TEXT,
	direction BOOLEAN
);

CREATE TABLE business_relationship_types (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT false,
	natural_person_enabled BOOLEAN NOT NULL DEFAULT false,
	legal_entity_enabled BOOLEAN NOT NULL DEFAULT false,
	code TEXT
);

-- NOTE: This table is no longer required as I'm using a dropdown box to list keep and list all the options
-- I will keep it for future reference
CREATE TABLE risk_class (
	id INTEGER PRIMARY KEY,
	code TEXT,
	description TEXT,
	rank INT,
	enabled BOOLEAN,
	hex_color TEXT
);

-- NOTE: This table is no longer required as I'm using a dropdown box to list keep and list all the options
-- I will keep it for future reference
CREATE TABLE product_types (
    id INTEGER PRIMARY KEY,
    enabled BOOLEAN,
    name TEXT,
    code TEXT,
    nature_of_sanlam_payout TEXT,
    default_risk_profile_id INTEGER
);

CREATE TABLE source_of_funds (
	id INTEGER PRIMARY KEY,
	enabled BOOLEAN NOT NULL DEFAULT FALSE,
	name TEXT NOT NULL,
	natural_person_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	legal_entity_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	code TEXT NOT NULL UNIQUE
);

INSERT INTO risk_class (code, description, rank, enabled, hex_color)
VALUES	('L', 'Low', 1, TRUE, '#008755'),
('M', 'Medium', 1, TRUE, '#f2a900'),
('H', 'High', 1, TRUE, '#cb333b'),
('HP', 'High Plus', 1, FALSE, '#825474'),
('LM', 'LOW MINUS', 1, FALSE, '#9db7b4'),
('I', 'Intolerable', 1, TRUE, '#01020A'),
('II', 'INTOLERABLES', 1, FALSE, 'Orange');

INSERT INTO source_of_funds (enabled, name, natural_person_enabled, legal_entity_enabled, code) VALUES
(TRUE, 'ALLOWANCE', TRUE, TRUE, 'ALLOWANCE'),
(TRUE, 'Bonus', TRUE, FALSE, 'BONUS'),
(TRUE, 'Bursary', TRUE, FALSE, 'BURSARY'),
(FALSE, 'COMMUTATION', TRUE, TRUE, 'COMMUTATION'),
(TRUE, 'Company profits', TRUE, TRUE, 'COMPANY PROFITS'),
(TRUE, 'Company sale / sale of interest in company', TRUE, TRUE, 'COMPANY SALE / SALE OF INTEREST IN COMPANY'),
(FALSE, 'Court Order', TRUE, FALSE, 'COURT ORDER'),
(TRUE, 'Cryptocurrency', TRUE, TRUE, 'CRYPTOCURRENCY'),
(TRUE, 'Debt Capital', TRUE, TRUE, 'DEBT CAPITAL'),
(FALSE, 'Deceased Estate', FALSE, FALSE, 'DECEASED ESTATE'),
(FALSE, 'DIRECTOR / MEMBER OF COMPANY', TRUE, FALSE, 'DIRECTOR / MEMBER OF COMPANY'),
(FALSE, 'Director / Own Business', TRUE, FALSE, 'DIRECTOR / OWN BUSINESS'),
(TRUE, 'Disability / Social grant', TRUE, FALSE, 'DISABILITY / SOCIAL GRANT'),
(TRUE, 'Dividends from Investments', TRUE, TRUE, 'DIVIDENDS FROM INVESTMENTS'),
(TRUE, 'Divorce Settlement', TRUE, FALSE, 'DIVORCE SETTLEMENT'),
(TRUE, 'Employee Benefits', FALSE, TRUE, 'EMPLOYEE BENEFITS'),
(FALSE, 'Encashment claim', FALSE, FALSE, 'ENCASHMENT CLAIM'),
(TRUE, 'Equity Capital', TRUE, TRUE, 'EQUITY CAPITAL'),
(TRUE, 'Gambling winnings', TRUE, FALSE, 'GAMBLING WINNINGS'),
(TRUE, 'Gift / Donation', TRUE, TRUE, 'GIFT / DONATION'),
(TRUE, 'Gratuity', TRUE, FALSE, 'GRATUITY'),
(TRUE, 'Income from previous employment', TRUE, FALSE, 'INCOME FROM PREVIOUS EMPLOYMENT'),
(TRUE, 'Inheritance', TRUE, TRUE, 'INHERITANCE'),
(TRUE, 'LOAN', TRUE, TRUE, 'LOAN'),
(TRUE, 'Lobola', TRUE, FALSE, 'LOBOLA'),
(FALSE, 'Lottery / Gambling winnings', TRUE, FALSE, 'LOTTERY / GAMBLING WINNINGS'),
(TRUE, 'Lottery winnings', TRUE, FALSE, 'LOTTERY WINNINGS'),
(TRUE, 'Maintenance (formal agreement)', TRUE, FALSE, 'MAINTENANCE (FORMAL AGREEMENT)'),
(TRUE, 'Maintenance (informal agreement)', TRUE, FALSE, 'MAINTENANCE (INFORMAL AGREEMENT)'),
(FALSE, 'Maintenance', TRUE, FALSE, 'MAINTENANCE'),
(TRUE, 'Maturing Investments', TRUE, TRUE, 'MATURING INVESTMENTS'),
(FALSE, 'Nature of Sanlam Payout : Full Disinvestments', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT : FULL DISINVESTMENTS'),
(FALSE, 'Nature of Sanlam Payout : Partial Disinvestments', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT : PARTIAL DISINVESTMENTS'),
(TRUE, 'SANLAM PAY-OUT', TRUE, TRUE, 'SANLAM PAY-OUT'),
(FALSE, 'Nature of Sanlam Payout: Ad-hoc Payment Claim (TRUST)', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: AD-HOC PAYMENT CLAIM (TRUST)'),
(FALSE, 'Nature Of Sanlam Payout: Annuity payments', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: ANNUITY PAYMENTS'),
(FALSE, 'Nature of Sanlam Payout: Death Claim Benefit', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: DEATH CLAIM BENEFIT'),
(FALSE, 'NATURE OF SANLAM PAYOUT: DISABILITY CLAIM', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: DISABILITY CLAIM'),
(FALSE, 'NATURE OF SANLAM PAYOUT: DIVIDEND PAYMENT', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: DIVIDEND PAYMENT'),
(FALSE, 'NATURE OF SANLAM PAYOUT: FINAL DISTRIBUTION/ TERMINATION (TRUST)', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: FINAL DISTRIBUTION/ TERMINATION (TRUST)'),
(FALSE, 'NATURE OF SANLAM PAYOUT: FULL SURRENDER', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: FULL SURRENDER'),
(FALSE, 'NATURE OF SANLAM PAYOUT: INCOME PROTECTION PAYMENT', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: INCOME PROTECTION PAYMENT'),
(FALSE, 'NATURE OF SANLAM PAYOUT: LOAN AGAINST PORTFOLIO OF INVESTMENTS', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: LOAN AGAINST PORTFOLIO OF INVESTMENTS'),
(FALSE, 'NATURE OF SANLAM PAYOUT: LUMP SUM DISABILITY', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: LUMP SUM DISABILITY'),
(FALSE, 'NATURE OF SANLAM PAYOUT: MATURITY OF INVESTMENT BENEFIT', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: MATURITY OF INVESTMENT BENEFIT'),
(FALSE, 'Nature of Sanlam Payout: Monthly Maintenance Claim (TRUST)', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: MONTHLY MAINTENANCE CLAIM (TRUST)'),
(FALSE, 'Nature of Sanlam Payout: Monthly Recurring Disability Claim', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: MONTHLY RECURRING DISABILITY CLAIM'),
(FALSE, 'Nature of Sanlam Payout: Partial Surrender', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: PARTIAL SURRENDER'),
(FALSE, 'Nature of Sanlam Payout: Personal Loan/Credit', TRUE, TRUE, 'NATURE OF SANLAM PAYOUT: PERSONAL LOAN/CREDIT'),
(FALSE, 'Nature of Sanlam Transaction: Premium Break/Relief', TRUE, TRUE, 'NATURE OF SANLAM TRANSACTION: PREMIUM BREAK/RELIEF'),
(FALSE, 'New Investment / Capital', FALSE, FALSE, 'NEW INVESTMENT / CAPITAL'),
(TRUE, 'Other', TRUE, TRUE, 'OTHER'),
(TRUE, 'Pension', TRUE, TRUE, 'PENSION'),
(FALSE, 'Private capital raise', FALSE, FALSE, 'PRIVATE CAPITAL RAISE'),
(TRUE, 'Provident Funds', TRUE, TRUE, 'PROVIDENT FUNDS'),
(FALSE, 'Public capital raise', TRUE, TRUE, 'PUBLIC CAPITAL RAISE'),
(FALSE, 'Rental from Property', TRUE, TRUE, 'RENTAL FROM PROPERTY'),
(TRUE, 'Retained Earnings', FALSE, TRUE, 'RETAINED EARNINGS'),
(TRUE, 'Retirement Funds', TRUE, TRUE, 'RETIREMENT FUNDS'),
(FALSE, 'SALARY / BONUS', TRUE, FALSE, 'SALARY / BONUS'),
(TRUE, 'Salary', TRUE, FALSE, 'SALARY'),
(TRUE, 'Sale asset / property', TRUE, TRUE, 'SALE ASSET / PROPERTY'),
(TRUE, 'Sale of Shares', TRUE, TRUE, 'SALE OF SHARES'),
(TRUE, 'SANLAM PAYOUT', TRUE, TRUE, 'SANLAM PAYOUT'),
(TRUE, 'Savings', TRUE, TRUE, 'SAVINGS'),
(TRUE, 'Settlement', TRUE, TRUE, 'SETTLEMENT'),
(TRUE, 'TRANSFER OF FUNDS', TRUE, TRUE, 'TRANSFER OF FUNDS'),
(TRUE, 'Transfer to/from approved funds', TRUE, TRUE, 'TRANSFER TO/FROM APPROVED FUNDS'),
(TRUE, 'Trust income', TRUE, TRUE, 'TRUST INCOME'),
(FALSE, 'Automation KT', TRUE, FALSE, 'DEMO5TH MAY 2023'),
(TRUE, 'BUSINESS OPERATING INCOME', TRUE, TRUE, 'BUSINESS OPERATING INCOME'),
(TRUE, 'COMMISSION', TRUE, TRUE, 'COMMISSION'),
(TRUE, 'RENTAL OF PROPERTY', TRUE, TRUE, 'RENTAL OF PROPERTY'),
(TRUE, 'Tax Rebate', TRUE, TRUE, 'TAX REBATE'),
(TRUE, 'MEMBER CONTRIBUTIONS', FALSE, TRUE, 'MEMBER CONTRIBUTIONS'),
(TRUE, 'TESTAUTOMATION', TRUE, TRUE, 'TESTAUTOMATION'),
(FALSE, 'TESTDEMO16AUG2024', TRUE, TRUE, 'TESTDEMOTEST'),
(TRUE, 'VIRTUAL CURRENCY', TRUE, FALSE, 'VIRTUAL CURRENCY');

INSERT INTO product_types (enabled, name, code, nature_of_sanlam_payout, default_risk_profile_id) VALUES
(TRUE, 'ADVISORY SERVICES', 'ADS', 'UNKNOWN', 1),
(TRUE, 'ALTERNATIVE INVESTMENTS', 'ALT', 'Invested Funds', 3),
(TRUE, 'ANNUITIES', 'ANN', 'Monthly Funds', 1),
(TRUE, 'ASSET MANAGEMENT', 'ASS', 'Invested Funds', 3),
(TRUE, 'BUNDLED RISK PRODUCTS', 'BRP', 'Insurance Claim', 1),
(TRUE, 'CAPITAL DISABILITY', 'CAP', 'Insurance Claim', 1),
(TRUE, 'DS:ASSET BACKED FINANCE', 'DSAB', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:BONDS', 'DSB', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:CREDIT DERIVATIVES', 'DSCD', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:COMMERCIAL PAPER', 'DSCP', 'Loan (SCM = Borrower)', 3),
(TRUE, 'DS:CURRENCY SWAPS', 'DSCS', 'Foreign Currency', 3),
(TRUE, 'DS:DEBT FUNDS', 'DSDF', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:EQUITY', 'DSE', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:EMPOWERMENT FUNDING', 'DSEP', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:STRUCTURED FINANCE', 'DSF', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:FOREIGN EXCHANGE CURRENCY FUTURES', 'DSFC', 'Hedging', 3),
(TRUE, 'DS:EQUITY HYBRID INSTRUMENTS', 'DSHI', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:INTEREST RATE SWAPS and OPTIONS', 'DSIS', 'Hedging', 3),
(TRUE, 'DS:MEZZANINE / SUBORDINATED FINANCE', 'DSMS', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:PROJECT FINANCE', 'DSPF', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:SYNDICATED and CLUB LOANS', 'DSSC', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:SECURITISATION', 'DST', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'DS:TERM FUNDING', 'DSTF', 'Loan (SCM = Lender)', 3),
(TRUE, 'ENDOWMENT POLICIES', 'END', 'Invested Funds', 2),
(TRUE, 'ES: HI: LISTED CURRENCY FUTURES', 'ESCF', 'Hedging', 3),
(TRUE, 'ES : ATI : EQUITIES (THROUGH SPW)', 'ESE', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'ES: HI :FUTURES OPTIONS LISTED ON SAFEX', 'ESFO', 'Hedging', 3),
(TRUE, 'ES: ATI: LOANS TO CLIENTS', 'ESLC', 'Loan', 3),
(TRUE, 'ES: ATI: LOANS FROM MONEY MARKET', 'ESLM', 'Loan', 3),
(TRUE, 'ES: HI: MONEY MARKET INSTRUMENTS', 'ESMM', 'Loan', 3),
(TRUE, 'ES: ATI: OTC DERIVATIVES ON SPECIFIC STOCKS OR INDICES', 'ESOD', 'Hedging', 3),
(TRUE, 'ES: HI: PREFERENCE SHARES', 'ESPS', 'Loan (SCM/CCM = Lender)', 3),
(TRUE, 'ES: ATI: SWAPS', 'ESS', 'Hedging', 3),
(TRUE, 'ESTATE PLANNING', 'ESTE', 'UNKNOWN', 1),
(TRUE, 'FUNERAL COVER', 'FUN', 'Insurance Claim', 1),
(TRUE, 'GLA VENDOR ADMINISTRATIVE SERVICES', 'GAV', NULL, 1),
(TRUE, 'GLA EXTERNAL PLATFORM SERVICES', 'GES', NULL, 1),
(TRUE, 'GLA Interim PT', 'GIP', NULL, 3),
(TRUE, 'HEALTH CARE PRODUCTS', 'HLT', 'Medical Benefits', 1),
(TRUE, 'INVESTMENT POLICY', 'INV', 'Invested Funds', 3),
(TRUE, 'INCOME PROTECTION', 'IPP', 'Monthly Insurance Claim', 1),
(TRUE, 'LIFE COVER', 'LIC', 'Insurance Claim', 1),
(TRUE, 'MULTI DATA COLLECTIONS', 'MDCS', 'UNKNOWN', 1),
(TRUE, 'MULTI DATA FILE TRANSFER', 'MDFT', 'UNKNOWN', 1),
(TRUE, 'MULTI DATA PRODUCT', 'MDP', 'UNKNOWN', 1),
(TRUE, 'MULTI DATA PAYMENTS', 'MDPS', 'UNKNOWN', 1),
(TRUE, 'PERSONAL LOANS', 'PERSL', 'Loan', 2),
(TRUE, 'RETIREMENT FUNDS', 'RET', 'Invested Funds', 1),
(TRUE, 'REWARDS PROGRAMME', 'REW', 'Loyalty Rewards', 1),
(TRUE, 'SAVINGS', 'SAV', 'Invested Funds', 2),
(TRUE, 'SHORT TERM INSURANCE', 'STI', 'Insurance Claim', 1),
(TRUE, 'TRUSTS', 'TRUS', 'Invested Funds', 1),
(TRUE, 'UNIT TRUSTS', 'UTS', 'Invested Funds', 2),
(TRUE, 'WILLS', 'WILL', 'UNKNOWN', 1),
(TRUE, 'DS: FOREIGN EXCHANGE', 'DSFE', NULL, 3),
(TRUE, 'Advisory services: Financial and investments', 'AFI', NULL, 2),
(TRUE, 'Ad hoc savings and investment: Non insurance (unit trust funds, discretionary share portfolios, cash management solutions)', 'ASIN', NULL, 2),
(TRUE, 'Advisory services: Non financial', 'ANF', NULL, 2),
(TRUE, 'Annuities and annuity contracts: Compulsory', 'AAC', NULL, 1),
(TRUE, 'Annuities and annuity contracts: Discretionary / Voluntary', 'AADV', NULL, 2),
(TRUE, 'Asset backed credit', 'ABC', NULL, 2),
(TRUE, 'Asset management: Institutional clients', 'AMI', NULL, 1),
(TRUE, 'Asset management: Retail', 'AMR', NULL, 2),
(TRUE, 'Cash management', 'CMN', NULL, 3),
(TRUE, 'Collection services', 'CSS', NULL, 3),
(TRUE, 'Deceased Estate and Will administration', 'DEW', NULL, 1),
(TRUE, 'Derivative Trading', 'DTD', NULL, 3),
(TRUE, 'Financial service provider: Intermediary service', 'FSPI', NULL, 2),
(TRUE, 'FINANCING SOLUTIONS : INSTITUTIONAL CREDIT', 'FSIC', NULL, 2),
(TRUE, 'Financing solutions : Retail credit', 'FSRC', NULL, 2),
(TRUE, 'Hedge Fund Regulated', 'HFR', NULL, 3),
(TRUE, 'Hedge Fund Unregulated', 'HFU', NULL, 3),
(TRUE, 'In Product Benefits', 'PBS', NULL, 1),
(TRUE, 'Insurance products: Retirement funds, group schemes and Institutional clients', 'IPRGI', NULL, 1),
(TRUE, 'Insurance risk cover', 'IRC', NULL, 1),
(TRUE, 'Insurance risk cover: Funeral', 'IRCF', NULL, 1),
(TRUE, 'Investment management / fund platform', 'IMF', NULL, 3),
(TRUE, 'Investment management: Institutional clients', 'IMI', NULL, 2),
(TRUE, 'Investment management: Retail clients', 'IMR', NULL, 2),
(TRUE, 'Listed Bond Solutions', 'LBS', NULL, 1),
(TRUE, 'Loyalty and Rewards', 'LAR', NULL, 1),
(TRUE, 'Market Making', 'MMK', NULL, 3),
(TRUE, 'Online Share Trading platform', 'OSTP', NULL, 3),
(TRUE, 'Payment service provider', 'PSP', NULL, 2),
(TRUE, 'Recurring premium savings insurance product', 'RPSI', NULL, 2),
(TRUE, 'Recurring savings and investment: Non insurance (unit trust funds, discretionary share portfolios, cash management solutions)', 'RSIN', NULL, 2),
(TRUE, 'Retail credit', 'RCT', NULL, 2),
(TRUE, 'Single premium savings insurance product', 'SPSI', NULL, 2),
(TRUE, 'Stock broking', 'SBG', NULL, 3),
(TRUE, 'Tax Free savings products', 'TFS', NULL, 2),
(TRUE, 'Trust administration', 'TAN', NULL, 2);

INSERT INTO industry_types (name, enabled, natural_person_enabled, legal_entity_enabled, code) VALUES
('Administrative and support services',1,1,1,'ADMINISTRATIVE and SUPPORT SERVICES'),
('Adult entertainment',1,1,1,'ADULT ENTERTAINMENT'),
('Agriculture, forestry and fishing',1,1,1,'AGRICULTURE, FORESTRY and FISHING'),
('Arts, entertainment and recreation',1,1,1,'ARTS, ENTERTAINMENT and RECREATION'),
('Broadcasting and entertainment',1,1,1,'BROADCASTING and ENTERTAINMENT'),
('Chemical engineering / manufacturing',1,1,1,'CHEMICAL ENGINEERING / MANUFACTURING'),
('Community and social activities',1,1,1,'COMMUNITY and SOCIAL ACTIVITIES'),
('Construction and civil engineering',1,1,1,'CONSTRUCTION and CIVIL ENGINEERING'),
('Consumer Goods: Wholesale and Retail',1,1,1,'CONSUMER GOODS: WHOLESALE and RETAIL'),
('Education',1,1,1,'EDUCATION'),
('Electricity, solar, water, gas and waste services',1,1,1,'ELECTRICITY, SOLAR, WATER, GAS and WASTE SERVICES'),
('Entrepreneurship',1,1,1,'ENTREPRENEURSHIP'),
('Estate, living and family trusts',1,1,1,'ESTATE, LIVING and FAMILY TRUSTS'),
('Extractive services, mining and quarrying',1,1,1,'EXTRACTIVE SERVICES, MINING and QUARRYING'),
('Financial and insurance',1,1,1,'FINANCIAL and INSURANCE'),
('Gambling',1,1,1,'GAMBLING'),
('Government services, arms and State Owned Enterprises',1,1,1,'GOVERNMENT SERVICES, ARMS and STATE OWNED ENTERPRISES'),
('HEALTHCARE and MEDICAL',1,1,1,'HEALTHCARE and MEDICAL'),
('Information technology, communication and telecoms',1,1,1,'INFORMATION TECHNOLOGY, COMMUNICATION and TELECOMS'),
('Legal practitioner',1,1,1,'LEGAL PRACTITIONER'),
('Manufacturing',1,1,1,'MANUFACTURING'),
('Motor wholesale, retail trade and repair',1,1,1,'MOTOR WHOLESALE, RETAIL TRADE and REPAIR'),
('Non profit organisation / regulated charity',1,1,1,'NON PROFIT ORGANISATION / REGULATED CHARITY'),
('Non-government organisation (NGO)',1,1,1,'NON-GOVERNMENT ORGANISATION (NGO)'),
('Other',1,1,1,'OTHER'),
('PFMA Schedule 1',0,1,1,'PFMA SCHEDULE 1'),
('PFMA Schedule 2',0,1,1,'PFMA SCHEDULE 2'),
('PFMA Schedule 3A',0,1,1,'PFMA SCHEDULE 3A'),
('Professional sport',1,1,1,'PROFESSIONAL SPORT'),
('Real estate and property services',1,1,1,'REAL ESTATE and PROPERTY SERVICES'),
('Shell banking',1,1,1,'SHELL BANKING'),
('Transport, storage, courier and freight',1,1,1,'TRANSPORT, STORAGE, COURIER and FREIGHT'),
('Travel, tourism, accommodation and food services',1,1,1,'TRAVEL, TOURISM, ACCOMMODATION and FOOD SERVICES'),
('Virtual currencies',1,1,1,'VIRTUAL CURRENCIES'),
('ACCOUNTING SERVICES',1,1,1,'ACCOUNTING SERVICES'),
('AEROSPACE & DEFENSE',1,1,1,'AEROSPACE & DEFENSE'),
('ARMS DEALERS',1,1,1,'ARMS DEALERS'),
('AUTOMOBILES & PARTS',1,1,1,'AUTOMOBILES & PARTS'),
('BANKS',1,1,1,'BANKS'),
('BEVERAGES',1,1,1,'BEVERAGES'),
('CANNABIS/CBD INDUSTRY',1,1,1,'CANNABIS/CBD INDUSTRY'),
('CASH AGGREGATORS',1,1,1,'CASH AGGREGATORS'),
('ELECTRONIC & ELECTRICAL EQUIPMENT',1,1,1,'ELECTRONIC & ELECTRICAL EQUIPMENT'),
('EQUITY INVESTMENT INSTRUMENTS',1,1,1,'EQUITY INVESTMENT INSTRUMENTS'),
('FOOD PRODUCERS',1,1,1,'FOOD PRODUCERS'),
('High Transaction Volume Import/Export Companies',1,1,1,'HIGH TRANSACTION VOLUME IMPORT/EXPORT COMPANIES'),
('HIGH VALUE GOODS DEALERS (INCLUDING MOTOR VEHICLE DEALERS, ART DEALERS, LUXURY GOODS/SERVICES Etc)',1,1,1,'HIGH VALUE GOODS DEALERS (INCLUDING MOTOR VEHICLE DEALERS, ART DEALERS, LUXURY GOODS/SERVICES Etc)'),
('HOUSEHOLD GOODS & HOME CONSTRUCTION MATERIALS',1,1,1,'HOUSEHOLD GOODS & HOME CONSTRUCTION MATERIALS'),
('INDUSTRIAL ENGINEERING',1,1,1,'INDUSTRIAL ENGINEERING'),
('INDUSTRIAL METALS',1,1,1,'INDUSTRIAL METALS'),
('MEDIA',1,1,1,'MEDIA'),
('MONEY TRANSFER / SERVICE BUSINESSES',1,1,1,'MONEY TRANSFER / SERVICE BUSINESSES'),
('NON EQUITY INVESTMENT INSTRUMENTS',1,1,1,'NON EQUITY INVESTMENT INSTRUMENTS'),
('OIL & GAS PRODUCERS / SUPPLIERS',1,1,1,'OIL & GAS PRODUCERS / SUPPLIERS'),
('PAWN BROKERS/SECOND Hand DEALERS',1,1,1,'PAWN BROKERS/SECOND Hand DEALERS'),
('PHARMACEUTICALS & BIOTECHNOLOGY',1,1,1,'PHARMACEUTICALS & BIOTECHNOLOGY'),
('PRECIOUS METALS and STONE DEALERS',1,1,1,'PRECIOUS METALS and STONE DEALERS'),
('PUBLIC FINANCE MANAGEMENT ACT SCHEDULE',1,1,1,'PUBLIC FINANCE MANAGEMENT ACT SCHEDULE'),
('RETIRED',1,1,1,'RETIRED'),
('SCRAP METAL INDUSTRY',1,1,1,'SCRAP METAL INDUSTRY'),
('TOBACCO',1,1,1,'TOBACCO'),
('MINOR / SCHOLAR',1,1,1,'MINOR / SCHOLAR'),
('STATE OWNED ENTERPRISES',1,1,1,'STATE OWNED ENTERPRISES'),
('GOVERNMENT SERVICES',1,1,1,'GOVERNMENT SERVICES'),
('REINSURANCE',1,1,1,'REINSURANCE'),
('INFORMAL TRADING',1,1,1,'INFORMAL TRADING'),
('DOMESTIC SERVICES / GARDENING SERVICES',0,1,1,'DOMESTIC SERVICES / GARDENING SERVICES');

INSERT INTO countries (name, code, display_order, enabled, risk_profile_id) VALUES
('andorra','AD',1,1,0),
('United Arab Emirates','AE',1,1,0),
('Afghanistan','AF',100,1,1),
('Antigua and Barbuda','AG',1,1,0),
('Anguilla','AI',1,1,0),
('Albania','AL',1,1,0),
('Armenia','AM',1,1,0),
('Angola','AO',1,1,0),
('Antarctica','AQ',1,1,0),
('Argentina','AR',1,1,0),
('American Samoa','AS',1,1,0),
('Austria','AT',1,1,0),
('Australia','AU',1,1,0),
('Aruba','AW',1,1,0),
('Auckland Islands','AX',1,1,0),
('Azerbaijan','AZ',1,1,0),
('Bosnia and Herzegovina','BA',1,1,0),
('Barbados','BB',1,1,0),
('Bangladesh','BD',1,1,0),
('Belgium','BE',1,1,0),
('Burkina Faso','BF',1,1,0),
('Bulgaria','BG',1,1,0),
('Bahrain','BH',1,1,0),
('Burundi','BI',1,1,0),
('Benin','BJ',1,1,0),
('Saint Barthalemy','BL',1,1,0),
('Bermuda','BM',1,1,0),
('Brunei Darussalam','BN',1,1,0),
('Bolivia','BO',1,1,0),
('Bonaire, Sint Eustatius and Saba','BQ',1,1,0),
('Brazil','BR',1,1,0),
('Bahamas','BS',1,1,0),
('Bahamas, The','BS',1,1,0),
('Bhutan','BT',1,1,0),
('Bouvet Island','BV',1,1,0),
('Botswana','BW',1,1,0),
('Burma','MM',1,1,0),
('Belarus','BY',1,1,0),
('Belize','BZ',1,1,0),
('Canada','CA',1,1,0),
('Cocos (Keeling) Islands','CC',1,1,0),
('Congo, Democratic Republic of the','CD',1,1,0),
('Central African Republic','CF',1,1,0),
('Congo','CG',1,1,0),
('Congo, Republic of the','CG',1,1,0),
('Switzerland','CH',1,1,0),
('Côte d''Ivoire','CI',1,1,0),
('Cote d Ivoire','CI',1,1,0),
('Cook Islands','CK',1,1,0),
('Chile','CL',1,1,0),
('Cameroon','CM',1,1,0),
('China','CN',1,1,0),
('Colombia','CO',1,1,0),
('Costa Rica','CR',1,1,0),
('Cuba','CU',1,1,0),
('Cape Verde','CV',1,1,0),
('Curacao','CW',1,1,0),
('Christmas Island','CX',1,1,0),
('Cyprus','CY',1,1,0),
('Czechia','CZ',1,1,0),
('Czech Republic','CZ',1,1,0),
('Germany','DE',1,1,0),
('Djibouti','DJ',1,1,0),
('Denmark','DK',1,1,0),
('Dominica','DM',1,1,0),
('Dominican Republic','DO',1,1,0),
('Algeria','DZ',1,1,0),
('Ecuador','EC',1,1,0),
('Estonia','EE',1,1,0),
('Egypt','EG',1,1,0),
('Western Sahara','EH',1,1,0),
('Eritrea','ER',1,1,0),
('Spain','ES',1,1,0),
('Ethiopia','ET',1,1,0),
('Finland','FI',1,1,0),
('Fiji','FJ',1,1,0),
('Falkland Islands (Malvinas)','FK',1,1,0),
('Micronesia, Federated States of','FM',1,1,0),
('Faroe Islands','FO',1,1,0),
('France','FR',1,1,0),
('Gabon','GA',1,1,0),
('United Kingdom','GB',1,1,0),
('Grenada','GD',1,1,0),
('Georgia','GE',1,1,0),
('French Guiana','GF',1,1,0),
('Guernsey','GG',1,1,0),
('Ghana','GH',1,1,0),
('Gibraltar','GI',1,1,0),
('Greenland','GL',1,1,0),
('Gambia','GM',1,1,0),
('Guinea','GN',1,1,0),
('Guadeloupe','GP',1,1,0),
('Equatorial Guinea','GQ',1,1,0),
('Greece','GR',1,1,0),
('South Georgia and the South Sandwich Islands','GS',1,1,0),
('Guatemala','GT',1,1,0),
('Guam','GU',1,1,0),
('Guinea-Bissau','GW',1,1,0),
('Guyana','GY',1,1,0),
('Hong Kong','HK',1,1,0),
('Heard Island and McDonald Islands','HM',1,1,0),
('Honduras','HN',1,1,0),
('Croatia','HR',1,1,0),
('Haiti','HT',1,1,0),
('Hungary','HU',1,1,0),
('Indonesia','ID',1,1,0),
('Ireland','IE',1,1,0),
('Israel','IL',1,1,0),
('Isle of Man','IM',1,1,0),
('Man, Isle of','IM',1,1,0),
('India','IN',1,1,0),
('British Indian Ocean Territory','IO',1,1,0),
('Iraq','IQ',1,1,0),
('Iran, Islamic Republic of','IR',1,1,0),
('Iran','IR',1,1,0),
('Iceland','IS',1,1,0),
('Italy','IT',1,1,0),
('Jersey','JE',1,1,0),
('Jamaica','JM',1,1,0),
('Jordan','JO',1,1,0),
('Japan','JP',1,1,0),
('Kenya','KE',1,1,0),
('Kyrgyzstan','KG',1,1,0),
('Cambodia','KH',1,1,0),
('Kiribati','KI',1,1,0),
('Comoros','KM',1,1,0),
('Saint Kitts and Nevis','KN',1,1,0),
('Korea, Democratic People''s Republic of','KP',1,1,0),
('Korea, Republic of','KR',1,1,0),
('Korea, North','KR',1,1,0),
('Korea, South','KR',1,1,0),
('Kuwait','KW',1,1,0),
('Cayman Islands','KY',1,1,0),
('Kazakhstan','KZ',1,1,0),
('Lao People''s Democratic Republic','LA',1,1,0),
('Laos','LA',1,1,0),
('Lebanon','LB',1,1,0),
('Saint Lucia','LC',1,1,0),
('Liechtenstein','LI',1,1,0),
('Sri Lanka','LK',1,1,0),
('Liberia','LR',1,1,0),
('Lesotho','LS',1,1,0),
('Lithuania','LT',1,1,0),
('Luxembourg','LU',1,1,0),
('Latvia','LV',1,1,0),
('Libya','LY',1,1,0),
('Morocco','MA',1,1,0),
('Monaco','MC',1,1,0),
('Moldova, Republic of','MD',1,1,0),
('Moldova','MD',1,1,0),
('Montenegro','ME',1,1,0),
('Saint Martin (French part)','MF',1,1,0),
('Madagascar','MG',1,1,0),
('Marshall Islands','MH',1,1,0),
('Macedonia, the Former Yugoslav Republic of','MK',1,1,0),
('North Macedonia, The Republic of','MK',1,1,0),
('Mali','ML',1,1,0),
('Myanmar','MM',1,1,0),
('Mongolia','MN',1,1,0),
('Macao','MO',1,1,0),
('Macau','MO',1,1,0),
('Northern Mariana Islands','MP',1,1,0),
('Martinique','MQ',1,1,0),
('Mauritania','MR',1,1,0),
('Montserrat','MS',1,1,0),
('Malta','MT',1,1,0),
('Mauritius','MU',1,1,0),
('Maldives','MV',1,1,0),
('Malawi','MW',1,1,0),
('Mexico','MX',1,1,0),
('Malaysia','MY',1,1,0),
('Mozambique','MZ',1,1,0),
('Namibia','NA',1,1,0),
('New Caledonia','NC',1,1,0),
('Niger','NE',1,1,0),
('Norfolk Island','NF',1,1,0),
('Nigeria','NG',1,1,0),
('Nicaragua','NI',1,1,0),
('Netherlands','NL',1,1,0),
('Netherlands Antilles','NL',1,1,0),
('Norway','NO',1,1,0),
('Nepal','NP',1,1,0),
('Nauru','NR',1,1,0),
('Niue','NU',1,1,0),
('New Zealand','NZ',1,1,0),
('Oman','OM',1,1,0),
('Panama','PA',1,1,0),
('Peru','PE',1,1,0),
('French Polynesia','PF',1,1,0),
('Papua New Guinea','PG',1,1,0),
('Philippines','PH',1,1,0),
('Pakistan','PK',1,1,0),
('Poland','PL',1,1,0),
('Saint Pierre and Miquelon','PM',1,1,0),
('Pitcairn','PN',1,1,0),
('Puerto Rico','PR',1,1,0),
('Palestine, State of','PS',1,1,0),
('Palestinian','PS',1,1,0),
('Palestine','PS',1,1,0),
('Portugal','PT',1,1,0),
('Palau','PW',1,1,0),
('Paraguay','PY',1,1,0),
('Qatar','QA',1,1,0),
('Reunion','RE',1,1,0),
('Region: Commonwealth of Independent States', 'RU', 1, 1, 0),
('Region: Crimea', 'UA', 1, 1, 0),
('Region: Gaza', 'PS', 1, 1, 0),
('Region: Jammu and Kashmir', 'IN', 1, 1, 0),
('Region: Kafia Kingi', 'SS', 1, 1, 0),
('Region: North Gaza', 'PS', 1, 1, 0),
('Region: Northern Gaza', 'PS', 1, 1, 0),
('Region: Northern Mali', 'ML', 1, 1, 0),
('Region: Russia', 'RU', 1, 1, 0),
('Region: West Bank', 'PS', 1, 1, 0),
('Romania','RO',1,1,0),
('Serbia','RS',1,1,0),
('Russian Federation','RU',1,1,0),
('Russia','RU',1,1,0),
('Rwanda','RW',1,1,0),
('Saudi Arabia','SA',1,1,0),
('Solomon Islands','SB',1,1,0),
('Seychelles','SC',1,1,0),
('Sudan','SD',1,1,0),
('Sweden','SE',1,1,0),
('Singapore','SG',1,1,0),
('Saint Helena, Ascension and Tristan da Cunha','SH',1,1,0),
('Slovenia','SI',1,1,0),
('Svalbard and Jan Mayen','SJ',1,1,0),
('Slovakia','SK',1,1,0),
('Sierra Leone','SL',1,1,0),
('San Marino','SM',1,1,0),
('Senegal','SN',1,1,0),
('Somalia','SO',1,1,0),
('Suriname','SR',1,1,0),
('South Sudan','SS',1,1,0),
('Sao Tome and Principe','ST',1,1,0),
('El Salvador','SV',1,1,0),
('Sint Maarten (Dutch part)','SX',1,1,0),
('Syrian Arab Republic','SY',1,1,0),
('Syria','SY',1,1,0),
('Eswatini','SZ',1,1,0),
('Turks and Caicos Islands','TC',1,1,0),
('Chad','TD',1,1,0),
('French Southern Territories','TF',1,1,0),
('Togo','TG',1,1,0),
('Thailand','TH',1,1,0),
('The Gambia','GM',1,1,0),
('Tajikistan','TJ',1,1,0),
('Tokelau','TK',1,1,0),
('Timor-Leste','TL',1,1,0),
('Turkmenistan','TM',1,1,0),
('Tunisia','TN',1,1,0),
('Tonga','TO',1,1,0),
('Turkey','TR',1,1,0),
('Trinidad and Tobago','TT',1,1,0),
('Tuvalu','TV',1,1,0),
('Taiwan, Province of China','TW',1,1,0),
('Taiwan','TW',1,1,0),
('Tanzania, United Republic of','TZ',1,1,0),
('Tanzania','TZ',1,1,0),
('Ukraine','UA',1,1,0),
('Uganda','UG',1,1,0),
('United States Minor Outlying Islands','UM',1,1,0),
('United States','US',1,1,0),
('Uruguay','UY',1,1,0),
('Uzbekistan','UZ',1,1,0),
('Holy See (Vatican City State)','VA',1,1,0),
('Saint Vincent and the Grenadines','VC',1,1,0),
('Venezuela, Bolivarian Republic of','VE',1,1,0),
('Venezuela','VE',1,1,0),
('Virgin Islands, British','VG',1,1,0),
('Virgin Islands, U.S.','VI',1,1,0),
('Vietnam','VN',1,1,0),
('Vanuatu','VU',1,1,0),
('Wallis and Futuna','WF',1,1,0),
('Samoa','WS',1,1,0),
('West Bank','PS',1,1,0),
('Yemen','YE',1,1,0),
('Mayotte','YT',1,1,0),
('South Africa','ZA',0,1,0),
('Zambia','ZM',1,1,0),
('Zimbabwe','ZW',1,1,0),
('Unknown','ZZ',1,1,0),
('Undetermined','ZZ',1,1,0),
('Kosovo','XK',1,1,0);

INSERT INTO business_relationship_types (name, enabled, natural_person_enabled, legal_entity_enabled, code) VALUES
('ANNUITANT', true, true, true, 'ANNUITANT'),
('APPLICANT', true, true, true, 'APPLICANT'),
('APPLICANT/ PLAN HOLDER', false, true, true, 'APPLICANT/ PLAN HOLDER'),
('AUTHORISED REPRESENTATIVE', false, true, false, 'AUTHORISED REPRESENTATIVE'),
('BENEFICIAL OWNERS (NATURAL)', false, true, false, 'BENEFICIAL OWNERS (NATURAL)'),
('BENEFICIAL OWNERS (NON-NATURAL)', false, false, true, 'BENEFICIAL OWNERS (NON-NATURAL)'),
('BENEFICIARY', true, true, true, 'BENEFICIARY'),
('BENEFICIARY/ NOMINEE', false, true, false, 'BENEFICIARY/ NOMINEE'),
('BOARD MEMBER', false, true, false, 'BOARD MEMBER'),
('CESSIONARY', true, true, true, 'CESSIONARY'),
('CIS INVESTOR', false, true, true, 'CIS INVESTOR'),
('Co-Investor', false, true, true, 'CO-INVESTOR'),
('COLLATERAL CESSIONARY', true, false, true, 'COLLATERAL CESSIONARY'),
('COLLATORAL CESSIONARY', false, true, true, 'COLLATORAL CESSIONARY'),
('CO-POLICY OWNER', false, true, true, 'CO-POLICY OWNER'),
('CURATOR', false, true, false, 'CURATOR'),
('DEPENDANT', false, true, false, 'DEPENDANT'),
('DIRECTOR', false, true, false, 'DIRECTOR'),
('EXECUTOR', false, true, false, 'EXECUTOR'),
('Financial Service Provider', false, false, true, 'FINANCIAL SERVICE PROVIDER'),
('FUND ANNUITANT', true, true, false, 'FUND ANNUITANT'),
('FUND MEMBER', false, true, false, 'FUND MEMBER'),
('FUND MEMBERS', false, true, false, 'FUND MEMBERS'),
('GUARANTOR', false, true, true, 'GUARANTOR'),
('Investee Company', true, false, true, 'INVESTEE COMPANY'),
('JOINT ANNUITANT', false, true, false, 'JOINT ANNUITANT'),
('JOINT OR CO-POLICY OWNER', false, true, false, 'JOINT OR CO-POLICY OWNER'),
('LEGAL GUARDIAN', false, true, false, 'LEGAL GUARDIAN'),
('LEGAL OWNER', false, true, false, 'LEGAL OWNER'),
('LIFE INSURED', false, true, false, 'LIFE INSURED'),
('MANAGER', false, true, false, 'MANAGER'),
('MEMBER', false, true, false, 'MEMBER'),
('MULTI DATA CLIENT', true, true, true, 'MULTI DATA CLIENT'),
('NOMINEE OF OWNERSHIP', true, true, true, 'NOMINEE OF OWNERSHIP'),
('NON-UNDERWITTEN LIVES (FUNERAL)', false, true, false, 'NON-UNDERWITTEN LIVES (FUNERAL)'),
('PARENT', false, true, false, 'PARENT'),
('PARLOUR (JURISTIC REPRESENTATIVE)', true, false, true, 'PARLOUR (JURISTIC REPRESENTATIVE)'),
('PARTNER', false, true, false, 'PARTNER'),
('PAYEE', false, true, true, 'PAYEE'),
('POLICY OWNER', true, true, true, 'POLICY OWNER'),
('POWER OF ATTORNEY', false, true, false, 'POWER OF ATTORNEY'),
('PREMIUM PAYER', true, true, true, 'PREMIUM PAYER'),
('SECONDARY BENEFICIARY', false, true, true, 'SECONDARY BENEFICIARY'),
('SHAREHOLDER', false, true, true, 'SHAREHOLDER'),
('SPOUSE', false, true, false, 'SPOUSE'),
('SURETY', false, true, true, 'SURETY'),
('THIRD PARTY PAYMENT', false, true, true, 'THIRD PARTY PAYMENT'),
('THIRD PARTY PAYMENTS', false, true, true, 'THIRD PARTY PAYMENTS'),
('TRUST BENEFICIARY', false, true, true, 'TRUST BENEFICIARY'),
('TRUST FOUNDER / DONOR', false, true, true, 'TRUST FOUNDER / DONOR'),
('TRUSTEE', true, true, true, 'TRUSTEE'),
('DECEASED', true, true, false, 'DECEASED');

INSERT INTO transaction_reasons (description, enabled, code, direction) VALUES
('Additional premium', TRUE, 'ADDITIONAL PREMIUM', TRUE),
('Cession to Financial Institution', TRUE, 'CESSION', TRUE),
('Client / policy change', TRUE, 'CLIENT / POLICY CHANGE', TRUE),
('Combined alteration', TRUE, 'COMBINED ALTERATION', TRUE),
('Commission / service fee', TRUE, 'COMMISSION / SERVICE FEE', TRUE),
('Continuation', TRUE, 'CONTINUATION', TRUE),
('Conversion', TRUE, 'CONVERSION', TRUE),
('New business', TRUE, 'NEW BUSINESS', TRUE),
('Premium arrears', TRUE, 'PREMIUM ARREARS', TRUE),
('RE-ISSUE WITH NO POLICY CHANGES', TRUE, 'RE-ISSUE WITH NO POLICY CHANGES', TRUE),
('RENEWAL WITH NO POLICY / FUND CHANGES', TRUE, 'RENEWAL WITH NO POLICY / FUND CHANGES', TRUE),
('Review underwriting', TRUE, 'REVIEW UNDERWRITING', TRUE),
('Switch in', TRUE, 'SWITCH IN', TRUE),
('Transfer of value (transfer in)', TRUE, 'TRANSFER OF VALUE (TRANSFER IN)', TRUE),
('Ad hoc payment claim', TRUE, 'AD HOC PAYMENT CLAIM', FALSE),
('Annuity / Income Payments', TRUE, 'ANNUITY / INCOME PAYMENTS', FALSE),
('Benefit payment', TRUE, 'BENEFIT PAYMENT', FALSE),
('Cash Flow Plan', TRUE, 'CASH FLOW PLAN', FALSE),
('Claim', TRUE, 'CLAIM', FALSE),
('Client / policy change out', TRUE, 'CLIENT / POLICY CHANGE OUT', FALSE),
('Commutation', TRUE, 'COMMUTATION', FALSE),
('Death claim', TRUE, 'DEATH CLAIM', FALSE),
('Disability claim', TRUE, 'DISABILITY CLAIM', FALSE),
('Dividend payment', TRUE, 'DIVIDEND PAYMENT', FALSE),
('Divorce', TRUE, 'DIVORCE', FALSE),
('External transfer', TRUE, 'EXTERNAL TRANSFER', FALSE),
('Final distribution / termination', TRUE, 'FINAL DISTRIBUTION / TERMINATION', FALSE),
('Full disinvestment', TRUE, 'FULL DISINVESTMENT', FALSE),
('Full repurchase (Redemption)', TRUE, 'FULL REPURCHASE (REDEMPTION)', FALSE),
('Full surrender', TRUE, 'FULL SURRENDER', FALSE),
('Income protection payment', TRUE, 'INCOME PROTECTION PAYMENT', FALSE),
('Internal transfer', TRUE, 'INTERNAL TRANSFER', FALSE),
('Loan', TRUE, 'LOAN', FALSE),
('Loan against Portfolio of Investments', TRUE, 'LOAN AGAINST PORTFOLIO OF INVESTMENTS', FALSE),
('Lump sum disability', TRUE, 'LUMP SUM DISABILITY', FALSE),
('Maturity of investment benefit', TRUE, 'MATURITY OF INVESTMENT BENEFIT', FALSE),
('Monthly maintenance claim', TRUE, 'MONTHLY MAINTENANCE CLAIM', FALSE),
('Partial disinvestment', TRUE, 'PARTIAL DISINVESTMENT', FALSE),
('Partial repurchase (partial redemption)', TRUE, 'PARTIAL REPURCHASE (PARTIAL REDEMPTION)', FALSE),
('Partial surrender', TRUE, 'PARTIAL SURRENDER', FALSE),
('Pension fund', TRUE, 'PENSION FUND', FALSE),
('Personal loan / credit', TRUE, 'PERSONAL LOAN / CREDIT', FALSE),
('Provident fund', TRUE, 'PROVIDENT FUND', FALSE),
('Recurring disability claim', TRUE, 'RECURRING DISABILITY CLAIM', FALSE),
('Refund', TRUE, 'REFUND', FALSE),
('Regular withdrawal', TRUE, 'REGULAR WITHDRAWAL', FALSE),
('Retirement', TRUE, 'RETIREMENT', FALSE),
('Switch out', TRUE, 'SWITCH OUT', FALSE),
('Termination', TRUE, 'TERMINATION', FALSE),
('Transfer of ownership', TRUE, 'TRANSFER OF OWNERSHIP', TRUE),
('Transfer of value', TRUE, 'TRANSFER OF VALUE', FALSE),
('Withdrawal', TRUE, 'WITHDRAWAL', FALSE),
('Annual Maintenance screening', TRUE, 'ANNUAL MAINTENANCE', TRUE),
('Cession to Non Financial Institution', TRUE, 'Cession to Non Financial Institution', TRUE),
('Re-issue with Policy changes', TRUE, 'RE-ISSUE WITH POLICY CHANGES', TRUE),
('RENEWAL WITH POLICY CHANGES OR ADDITIONAL FUNDS', TRUE, 'RENEWAL WITH POLICY CHANGES OR ADDITIONAL FUNDS', TRUE),
('Annual Maintenance Screening', TRUE, 'ANNUAL MAINTENANCE SCREENING', FALSE),
('LOAN REPAYMENT', TRUE, 'LOAN REPAYMENT', TRUE),
('WEEKLY MAINTENANCE', TRUE, 'WEEKLY MAINTENANCE', TRUE);
