/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.banelemlamleli.batchfilecreator;

/**
 *
 * @author banele
 */
public class BatchFileCreator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BatchFileCreator.class.getName());

    /**
     * Creates new form BatchFileCreator
     */
    public BatchFileCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNPLinkedParty = new javax.swing.JTextField();
        txtNaturalPersonMasterParty = new javax.swing.JTextField();
        txtLELinkedParty = new javax.swing.JTextField();
        txtNPLegalEntityMasterParty = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtNPNaturalPersonMasterParty = new javax.swing.JTextField();
        cmbNPCombination = new javax.swing.JComboBox<>();
        cmbNPWhichPartyMustAlert = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNaturalPersonLinkedParty = new javax.swing.JTextField();
        txtLegalEntityMasterParty = new javax.swing.JTextField();
        txtLegalEntityLinkedParty = new javax.swing.JTextField();
        txtLEMasterParty = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtNPMasterParty = new javax.swing.JTextField();
        cmbLECombination = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbLEWhichPartyMustAlert = new javax.swing.JComboBox<>();
        btnDownloadTxtFile = new javax.swing.JButton();
        btnDownloadCsvFile = new javax.swing.JButton();
        btnDownloadExcelFile = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmHomePage"); // NOI18N
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NATURAL PERSON", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setPreferredSize(new java.awt.Dimension(417, 348));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 2, 10)); // NOI18N
        jLabel2.setText("Legal Entity Linked Party:");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 2, 10)); // NOI18N
        jLabel3.setText("Natural Person Linked Party:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel4.setText("Legal Entity Master Party");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel5.setText("Natural Person Master Party:");

        txtNPLinkedParty.addActionListener(this::txtNPLinkedPartyActionPerformed);
        txtNPLinkedParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPLinkedPartyKeyTyped(evt);
            }
        });

        txtNaturalPersonMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNaturalPersonMasterPartyKeyTyped(evt);
            }
        });

        txtLELinkedParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLELinkedPartyKeyTyped(evt);
            }
        });

        txtNPLegalEntityMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPLegalEntityMasterPartyKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel13.setText("Natural Person Master Party");

        txtNPNaturalPersonMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPNaturalPersonMasterPartyKeyTyped(evt);
            }
        });

        cmbNPCombination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cmbNPWhichPartyMustAlert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "All parties", "Linked parties", "One NP linked party", "One LE linked party" }));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel12.setText("Which party must alert:");

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel15.setText("Combinations:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNPNaturalPersonMasterParty)
                    .addComponent(txtNPLegalEntityMasterParty)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNaturalPersonMasterParty)
                    .addComponent(txtNPLinkedParty)
                    .addComponent(txtLELinkedParty)
                    .addComponent(cmbNPWhichPartyMustAlert, 0, 221, Short.MAX_VALUE)
                    .addComponent(cmbNPCombination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNPCombination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cmbNPWhichPartyMustAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNaturalPersonMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLELinkedParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNPLinkedParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNPLegalEntityMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNPNaturalPersonMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LEGAL ENTITY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel6.setText("Combinations:");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 2, 10)); // NOI18N
        jLabel7.setText("Legal Entity Linked Party:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 2, 10)); // NOI18N
        jLabel8.setText("Natural Person Linked Party:");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel9.setText("Legal Entity Master Party");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel10.setText("Legal Entity Master Party:");

        txtNaturalPersonLinkedParty.addActionListener(this::txtNaturalPersonLinkedPartyActionPerformed);
        txtNaturalPersonLinkedParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNaturalPersonLinkedPartyKeyTyped(evt);
            }
        });

        txtLegalEntityMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegalEntityMasterPartyKeyTyped(evt);
            }
        });

        txtLegalEntityLinkedParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegalEntityLinkedPartyKeyTyped(evt);
            }
        });

        txtLEMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLEMasterPartyKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel14.setText("Natural Person Master Party");

        txtNPMasterParty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNPMasterPartyKeyTyped(evt);
            }
        });

        cmbLECombination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel11.setText("Which party must alert:");

        cmbLEWhichPartyMustAlert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "All parties", "Linked parties", "One NP linked party", "One LE linked party" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLEMasterParty)
                            .addComponent(txtNPMasterParty)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLegalEntityLinkedParty, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNaturalPersonLinkedParty)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLEWhichPartyMustAlert, 0, 225, Short.MAX_VALUE)
                            .addComponent(txtLegalEntityMasterParty)
                            .addComponent(cmbLECombination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLECombination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLEWhichPartyMustAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtLegalEntityMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLegalEntityLinkedParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNaturalPersonLinkedParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLEMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNPMasterParty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9))
        );

        btnDownloadTxtFile.setBackground(new java.awt.Color(153, 204, 255));
        btnDownloadTxtFile.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnDownloadTxtFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txt.png"))); // NOI18N
        btnDownloadTxtFile.setText("DOWNLOAD TXT FILE");
        btnDownloadTxtFile.setMaximumSize(new java.awt.Dimension(158, 29));
        btnDownloadTxtFile.setMinimumSize(new java.awt.Dimension(158, 29));
        btnDownloadTxtFile.setPreferredSize(new java.awt.Dimension(158, 29));
        btnDownloadTxtFile.addActionListener(this::btnDownloadTxtFileActionPerformed);

        btnDownloadCsvFile.setBackground(new java.awt.Color(255, 204, 204));
        btnDownloadCsvFile.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnDownloadCsvFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/csv.png"))); // NOI18N
        btnDownloadCsvFile.setText("DOWNLOAD CSV FILE");
        btnDownloadCsvFile.setMaximumSize(new java.awt.Dimension(158, 29));
        btnDownloadCsvFile.setMinimumSize(new java.awt.Dimension(158, 29));
        btnDownloadCsvFile.setPreferredSize(new java.awt.Dimension(158, 29));

        btnDownloadExcelFile.setBackground(new java.awt.Color(204, 255, 204));
        btnDownloadExcelFile.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnDownloadExcelFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excel.png"))); // NOI18N
        btnDownloadExcelFile.setText("DOWNLOAD EXCEL FILE");
        btnDownloadExcelFile.setMaximumSize(new java.awt.Dimension(158, 29));
        btnDownloadExcelFile.setMinimumSize(new java.awt.Dimension(158, 29));
        btnDownloadExcelFile.setPreferredSize(new java.awt.Dimension(158, 29));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batch_file.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel17.setText("B A T C H   F I L E   C R E A T O R  ( B F C )");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batch_file.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDownloadTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownloadCsvFile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnDownloadExcelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel18)
                .addGap(39, 39, 39)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDownloadTxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownloadExcelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownloadCsvFile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Batch File Creator (BFC)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadTxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadTxtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadTxtFileActionPerformed

    private void txtNPLinkedPartyActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void txtNaturalPersonLinkedPartyActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void txtLegalEntityMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char legalEntityMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(legalEntityMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtLegalEntityLinkedPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char legalEntityLinkedPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(legalEntityLinkedPartyKeyTyped))){
            evt.consume();
        }        
    }

    private void txtNaturalPersonLinkedPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char naturalPersonLinkedPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(naturalPersonLinkedPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtLEMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char lEMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(lEMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtNPMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char nPMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(nPMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtNaturalPersonMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char naturalPersonMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(naturalPersonMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtLELinkedPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char lELinkedPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(lELinkedPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtNPLinkedPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char nPLinkedPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(nPLinkedPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtNPLegalEntityMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char nPLegalEntityMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(nPLegalEntityMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    private void txtNPNaturalPersonMasterPartyKeyTyped(java.awt.event.KeyEvent evt) {
        char nPNaturalPersonMasterPartyKeyTyped = evt.getKeyChar();
        if(!(Character.isDigit(nPNaturalPersonMasterPartyKeyTyped))){
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BatchFileCreator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadCsvFile;
    private javax.swing.JButton btnDownloadExcelFile;
    private javax.swing.JButton btnDownloadTxtFile;
    private javax.swing.JComboBox<String> cmbLECombination;
    private javax.swing.JComboBox<String> cmbLEWhichPartyMustAlert;
    private javax.swing.JComboBox<String> cmbNPCombination;
    private javax.swing.JComboBox<String> cmbNPWhichPartyMustAlert;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtLELinkedParty;
    private javax.swing.JTextField txtLEMasterParty;
    private javax.swing.JTextField txtLegalEntityLinkedParty;
    private javax.swing.JTextField txtLegalEntityMasterParty;
    private javax.swing.JTextField txtNPLegalEntityMasterParty;
    private javax.swing.JTextField txtNPLinkedParty;
    private javax.swing.JTextField txtNPMasterParty;
    private javax.swing.JTextField txtNPNaturalPersonMasterParty;
    private javax.swing.JTextField txtNaturalPersonLinkedParty;
    private javax.swing.JTextField txtNaturalPersonMasterParty;
    // End of variables declaration//GEN-END:variables
}
